-- Server: sdsyb88
-- Table:  tbl_weblead_input
-- Date:   2019/4/17 17:58

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('01bea6da28a64323', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:44:23.816', '10:44:23', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I dada -', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('0666cf588c1545dc', '3', 'blc00000000', ' ', '+6565300862', 'test@aia.com', '2019-03-21 09:43:16.643', '09:43:16', 'y', 'Mdm.', 'blc6499593906', ' ', 'test gera', 'Be Life Confident - Millennials', 'web portal', 'Y', 'test', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('073e55b4a2ae4432', '1', 'pdt00000000', 'S2562323A', '+6583386316', 'agneskeh@yahoo.com', '2019-01-02 12:44:39.803', '12:44:39', 'Y', 'Mdm.', 'pdt9630476719', ' ', 'Agnes Tan', 'aia vitality', 'web portal', 'N', 'Would like to know how to remove team member and add a new member in the new app? Have been calling your 1800 248 8000 but unable to speak to any of your customer care consultants.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('0c1b6ae9365241da', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:34:55.12', '10:34:55', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'To be, or not to be', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('0d5312f8d98d492b', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:35:21.166', '10:35:21', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'To be, or not to be''', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('197aa893834540c7', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 11:41:16.313', '11:41:16', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', '&039I dsdw&039', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('3ade68b401d04a02', '3', 'blc00000000', ' ', '+6565300862', 'test@aia.com', '2019-03-21 13:26:08.476', '13:26:08', 'y', 'Miss.', 'blc1231735948', ' ', 'test gera', 'Be Life Confident - Pre Retiree', 'web portal', 'Y', 'test', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('3c51851751314a6b', '1', 'pdt00000000', 'S1381617D', '+6598266888', 'mikelim22@gmail.com', '2019-01-01 14:19:23.593', '14:19:23', 'Y', 'Mr.', 'pdt1580871516', ' ', 'Michael Lim', 'aia vitality', 'web portal', 'N', ' ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('3ffef5d09511485f', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:35:29.356', '10:35:29', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'To be, or not to be', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('45be76437e854262', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:57:15.26', '10:57:15', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I will inspire my Family and Children to - lead -_Healthier, longer, better lives in 2019 using the FEED method  Flex our mind in Positive Ways such as finding new ways of doing everyday things.   Eating Fewer Calories food such as fatty meats and adding more vegetables, fruits, and whole grains to our meals.  Exercising together such as playing basketball, jogging, and swimming to attain a better quality of life as we age. Finally, doing something together such as doing Art and Craft and Cooking Activities to bond together as a Family.', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('54c348c03920429a', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:34:19.473', '10:34:19', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', '''To be, or not to be''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('642623820c0f426b', '4', 'cus00000000', '123456', '11', 'jesus-sh.jin@aia.com', '2019-04-10 14:19:39.156', '14:19:39', 'n', 'Mr.', 'cust4740489089', ' ', 'aa', NULL, 'web portal', 'N', 'test', NULL, '12/12/2018', 'mother', '12/12/2018', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('854e7840ff694c36', '1', 'pdt00000000', 'S8576985E', '+6581141888', 'Prinechette@live.com', '2019-01-02 08:25:02.836', '08:25:02', 'Y', 'Miss.', 'pdt2051431954', ' ', 'Prinechette Delfino', 'aia vitality', 'web portal', 'N', 'How do i sign up for aia vitality?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('90bd3a15235248c2', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:56:57.21', '10:56:57', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I will inspire my Family and Children to - lead -Healthier, longer, better lives in 2019 using the FEED method  Flex our mind in Positive Ways such as finding new ways of doing everyday things.   Eating Fewer Calories food such as fatty meats and adding more vegetables, fruits, and whole grains to our meals.  Exercising together such as playing basketball, jogging, and swimming to attain a better quality of life as we age. Finally, doing something together such as doing Art and Craft and Cooking Activities to bond together as a Family.', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('98665d37c73d426b', '2', 'pdp00000000', 'NRIC', '+6596899169', 'beatrice.zoellner@gmail.com', '2019-02-22 08:43:38.166', '08:43:38', 'y', 'Miss.', 'pdp4179323455', ' ', 'Beatrice', 'direct - aia term cover', 'web portal', 'Y', 'please contact only via email', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('9e9f3a489b8249d8', '2', 'pdt00000000', 'S0175823C', '+6597770810', 'heehua_tan@yahoo.com.sg', '2019-02-28 16:11:57.876', '16:11:57', 'y', 'Mr.', 'pdt3031668165', ' ', 'Tan Hee Hua', 'AIA Around the World Plus', 'web portal', 'Y', ' ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419565262234472', '1', 'PSG00000000', ' ', 'p:+6590025982', 'hariniv80@gmail.com', '2019-01-23', '00:00:00', 'y', 'mdm', 'PSG:419565262234472', NULL, 'Harini Ranganathan', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419647655559566', '1', 'PSG00000000', ' ', 'p:+6598513780', 'franciscachonglc@gmail.com', '2019-01-23', '00:00:00', 'y', 'mdm', 'PSG:419647655559566', NULL, 'Francisca Chong', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419651035559228', '1', 'PSG00000000', ' ', 'p:+6596507658', 'huangsuzhen1345@gmail.com', '2019-01-23', '00:00:00', 'y', 'mdm', 'PSG:419651035559228', NULL, 'Khoo En Le David', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419704765553855', '1', 'PSG00000000', ' ', 'p:+6591263025', 'leezhiyi.veg@gmail.com', '2019-01-23', '00:00:00', 'n', 'miss', 'PSG:419704765553855', NULL, 'Lee Zhi Yi', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419721635552168', '1', 'PSG00000000', ' ', 'p:+6597554665', 'tan_woon_hui@hotmail.com', '2019-01-23', '00:00:00', 'n', 'mr', 'PSG:419721635552168', NULL, 'Tan Woon Hui', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419780652212933', '1', 'PSG00000000', ' ', 'p:+6590294071', 'vineetrvce@gmail.com', '2019-01-23', '00:00:00', 'n', 'mr', 'PSG:419780652212933', NULL, 'Vineet Golchha', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419781005546231', '1', 'PSG00000000', ' ', 'p:+6597517542', 'everlastinglovexp@gmail.com', '2019-01-23', '00:00:00', 'n', 'miss', 'PSG:419781005546231', NULL, 'Angie Ye', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419818578875807', '1', 'PSG00000000', ' ', 'p:+6594563361', 'shaoxuanluo.2011@business.smu.edu.sg', '2019-01-23', '00:00:00', 'n', 'mr', 'PSG:419818578875807', NULL, 'Gabriel Luo', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419840618873603', '1', 'PSG00000000', ' ', 'p:+6591069206', 'hairul.hakkim@gmail.com', '2019-01-23', '00:00:00', 'n', 'mr', 'PSG:419840618873603', NULL, 'Hairul Hakkim', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419842185540113', '1', 'PSG00000000', ' ', 'p:+6598386930', 'nicholas_lee_89@hotmail.com', '2019-01-23', '00:00:00', 'n', 'mr', 'PSG:419842185540113', NULL, 'Nicholas Lee', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419878455536486', '1', 'PSG00000000', ' ', 'p:+6597353846', 'johnny.chuacn@gmail.com', '2019-01-24', '00:00:00', 'n', 'mr', 'PSG:419878455536486', NULL, 'Johnny Chua', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419893518868313', '1', 'PSG00000000', ' ', 'p:+6590032807', 'hwa.ming@hotmail.com', '2019-01-24', '00:00:00', 'n', 'mr', 'PSG:419893518868313', NULL, 'Hwa Ming', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:419894042201594', '1', 'PSG00000000', ' ', 'p:+6594560170', 'budeilho@yahoo.com.sg', '2019-01-24', '00:00:00', 'n', 'miss', 'PSG:419894042201594', NULL, 'EN Lim', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('PSG:420041928853472', '1', 'PSG00000000', ' ', 'p:+6590065753', 'limchristine119@gmail.com', '2019-01-24', '00:00:00', 'n', 'miss', 'PSG:420041928853472', NULL, 'Christine Lim', 'AIA_Tranche_Lead Gen_V5', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('a9eb16b2ac4b415e', '4', 'pdt00000000', ' ', '+6581234567', 'iehowe@apdgroup.com', '2019-04-11 16:39:37.283', '16:39:37', 'y', 'Mr.', 'pdt5061349736', 'phone', 'APD Test-nric is empty', 'AIA Vitality', 'web portal', 'N', 'APD Testing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('afec264428f14b15', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 11:15:58.126', '11:15:58', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I will inspire my Family and Children   to - lead -_Healthier, longer, better lives in 2019 using the FEED method  Flex our mind in Positive Ways such as finding new ways of doing everyday things.   Eating Fewer Calories food such as fatty meats and adding more vegetables, fruits, and whole grains to our meals.  Exercising together such as playing basketball, jogging, and swimming to attain a better quality of life as we age. Finally, doing something together such as doing Art and Craft and Cooking Activities to bond together as a Family.', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('b2c4f751be034bae', '4', 'cus00000000', '123456', '11', 'jesus-sh.jin@aia.com', '2019-04-10 10:08:07.543', '10:08:07', 'n', 'Mr.', 'cust4740489089', ' ', 'aa', NULL, 'web portal', 'Y', 'test', NULL, '12/12/2018', 'mother', '12/12/2018', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('b3450c3be0c043ba', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:46:20.086', '10:46:20', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I will inspire my Family and Children to lead Healthier, longer, better lives in 2019 using the FEED method  Flex our mind in Positive Ways such as finding new ways of doing everyday things.   Eating Fewer Calories food such as fatty meats and adding more vegetables, fruits, and whole grains to our meals.  Exercising together such as playing basketball, jogging, and swimming to attain a better quality of life as we age. Finally, doing something together such as doing Art and Craft and Cooking Activities to bond together as a Family.', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('b487ac82e9cb4087', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:45:03.416', '10:45:03', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I dada -', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('b573c2f45f034022', '1', 'pdt00000000', 'S1539295I', '+6593855736', 'shirleyanglite@gmail.com', '2019-01-01 14:21:02.91', '14:21:02', 'Y', 'Mdm.', 'pdt7953704596', ' ', 'Ang Geok Har', 'aia vitality', 'web portal', 'N', ' ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('b99a34d6b9ef45b9', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 11:46:09.136', '11:46:09', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', '&039&039&039&039&039I dsdw&039', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('bf6f40210ff44e0c', '2', 'pdt00000000', 'S8080370B', '+6581885051', ' ', '2019-02-25 14:03:15.81', '14:03:15', 'Y', 'Mr.', 'pdt3943405014', ' ', 'NG CHUN SIUNG', 'aia vitality', 'web portal', 'N', ' ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('blc:384408875726769', '3', 'BLC00000000', ' ', 'p:+6590270903', 'chuabl79@yahoo.com', '2019-03-24', '00:00:00', 'y', 'mdm', 'blc:384408875726769', NULL, 'Shermaine Chua Bee Lin', 'AIA BLC Young Achievers 200319', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('blc:385017345665922', '3', 'BLC00000000', ' ', 'p:+6594281526', 'klk1627@hotmail.com', '2019-03-26', '00:00:00', 'y', 'mdm', 'blc:385017345665922', NULL, 'Chandra Kala Ratnasamy', 'AIA BLC Young Achievers 200319', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('blc:385435725624084', '3', 'BLC00000000', ' ', 'p:+6591238720', 'kongaurelia.sg@gmail.com', '2019-03-26', '00:00:00', 'y', 'miss', 'blc:385435725624084', NULL, 'Lindsey Aeryn Toh', 'AIA BLC Young Achievers 200319', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('blc:387936378707352', '3', 'BLC00000000', ' ', 'p:+6596879107', 'phllim123@yahoo.com', '2019-03-31', '00:00:00', 'y', 'mdm', 'blc:387936378707352', NULL, 'Linda Lim', 'AIA BLC Young Achievers 200319', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('blc:388131498687840', '3', 'BLC00000000', ' ', 'p:+6596197208', 'pcwong05@gmail.com', '2019-03-31', '00:00:00', 'y', 'miss', 'blc:388131498687840', NULL, 'Wong Pei Ching', 'AIA BLC Young Achievers 200319', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('c03ae4e5979e4ee2', '2', 'pdt00000000', 's7011109h', '+6591808878', 'harrylee@boaweb.com', '2019-02-28 14:28:20.83', '14:28:20', 'Y', 'Mr.', 'pdt0805544146', ' ', 'Harry Lee', 'aia vitality', 'web portal', 'N', 'I am a corporate client and I am interested in the AIA vitality program for personal use.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('c92256acd6464150', '1', 'pdt00000000', 'S7503521G', '+6597854587', 'valerieyml@gmail.com', '2019-01-02 11:43:00.026', '11:43:00', 'Y', 'Miss.', 'pdt6015263488', ' ', 'Yong Mei Leng', 'aia vitality', 'web portal', 'N', 'Would like to sign up the vitality program. Please advise.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('d2ad700c535f4c73', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 11:18:10.2', '11:18:10', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', '&039&039I will inspire my Family and Children   to - lead -_Healthier, longer, better lives in 2019 using the FEED method  Flex our mind in Positive Ways such as finding new ways of doing everyday things.   Eating Fewer Calories food such as fatty meats and adding more vegetables, fruits, and whole grains to our meals.  Exercising together such as playing basketball, jogging, and swimming to attain a better quality of life as we age. Finally, doing something together such as doing Art and Craft and Cooking Activities to bond together as a Family.', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('d740c044b54a4173', '1', 'pdt00000000', 'G3294730T', '+6591221732', 'bharathengg4@gmail.com', '2019-01-02 17:04:48.506', '17:04:48', 'y', 'Mr.', 'pdt0893139415', ' ', 'Bharath', 'AIA Mum2Baby Choices', 'web portal', 'Y', 'Need to discuss to know more about maternity insurance for my wife', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('e09f2186510243f2', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:44:11.246', '10:44:11', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I will inspire my Family and Children to lead Healthier, longer, better lives in 2019 using the FEED method Flex our mind in Positive Ways such as finding new ways of doing everyday things.', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('e455ce48209a4d0d', '1', 'pdt00000000', 'S7234972E', '+6596959044', 'jewelclz72@gmail.com', '2019-01-02 16:52:13.37', '16:52:13', 'Y', 'Miss.', 'pdt9213302148', ' ', 'Ching Liew Chun', 'aia vitality', 'web portal', 'N', 'How do I login to AIA Vitality app on my iphone?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('e52cb74d350a4880', '1', 'pdt00000000', 'G6139684K', '+6596697873', 'Camliong@gmail.com', '2019-01-01 15:09:03.486', '15:09:03', 'y', 'Miss.', 'pdt7359806954', ' ', 'Camilla', 'AIA HealthShield Gold Max', 'web portal', 'Y', 'Personal health insurance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('e6040f5a55a44e09', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 11:39:12.053', '11:39:12', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I will inspire my Family and Children to lead Healthier, longer, better lives in 2019 using the FEED method  Flex our mind in Positive Ways such as finding new ways of doing everyday things. Eating Fewer Calories food such as fatty meats and adding more vegetables, fruits, and whole grains to our meals. Exercising together such as playing basketball, jogging, and swimming to attain a better quality of life as we age. Finally, doing something together such as doing Art and Craft and Cooking Activities to bond together as a Family.', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('ea203a93a0d64d9f', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 10:42:49.563', '10:42:49', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I will inspire my Family and Children to lead Healthier,', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('efe923bc35dd4e23', '2', 'pdt00000000', 's8509557i', '+6586089755', 'iana.document@gmail.com', '2019-02-25 14:03:47.663', '14:03:47', 'y', 'Mdm.', 'pdt3934148268', ' ', 'Jamiana', 'AIA Mum2Baby Choices', 'web portal', 'Y', ' ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('fb0e22fbc63646cd', '4', 'cus00000000', ' ', NULL, ' ', '2019-04-09 18:54:46.78', '18:54:46', 'n', 'Mr.', 'cust4740489089', ' ', 'aa', NULL, 'web portal', 'Y', 'test', NULL, '12/12/2018', 'mother', '12/12/2018', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('fe5f02e5d4b64481', '1', 'WYW00000000', ' ', NULL, 'gsim_sin2@yahoo.com', '2019-01-31 11:13:52.143', '11:13:52', 'y', 'Mdm.', 'WYW7453438236', ' ', 'SIM GUET PENG GINA', '#WHATSYOURWHY - AIA Singapore', 'web portal', 'Y', 'I will inspire my Family and Children to - lead -_Healthier, longer, better lives in 2019 using the FEED method  Flex our mind in Positive Ways such as finding new ways of doing everyday things.   Eating Fewer Calories food such as fatty meats and adding more vegetables, fruits, and whole grains to our meals.  Exercising together such as playing basketball, jogging, and swimming to attain a better quality of life as we age. Finally, doing something together such as doing Art and Craft and Cooking Activities to bond together as a Family.', 'repeated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('psg239928876927019', '1', 'psg00000000', ' ', 'p:+6593276101', 'lulugal_90@hotmail.com', '2019-01-11', '00:00:00', 'y', 'miss', 'psg239275756992331', NULL, 'Lusandra Neo', 'AIA_Tranche_Lead Gen_V4', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('psg239940833592490', '1', 'psg00000000', ' ', 'p:+6582889652', 'glen_choo90@hotmail.com', '2019-01-11', '00:00:00', 'y', 'mr', 'psg239275756992331', NULL, 'Glen Choo', 'AIA_Tranche_Lead Gen_V4', 'fb', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:2237821906535721', '3', 'PYP00000000', ' ', 'p:+6585691299', 'jonathanang2501@outlook.sg', '2019-03-24', '00:00:00', 'y', 'mr', 'pyp:2237821906535721', NULL, 'Jonathan', 'Expectant Parents Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:2238758319775413', '3', 'PYP00000000', ' ', 'p:+6587531772', 'love_geetha@hotmail.com', '2019-03-26', '00:00:00', 'y', 'ms', 'pyp:2238758319775413', NULL, 'Love', 'Expectant Parents Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:2240383636279548', '3', 'PYP00000000', ' ', 'p:+6590684600', 'eamimra@yahoo.com', '2019-03-28', '00:00:00', 'y', 'mrs', 'pyp:2240383636279548', NULL, 'Armi', 'Expectant Parents Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:2240400679611177', '3', 'PYP00000000', ' ', 'p:+6596681297', 'ho.wei.zhe@gmail.com', '2019-03-28', '00:00:00', 'y', 'mr', 'pyp:2240400679611177', NULL, 'Aaron', 'Expectant Parents Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:2241766096141302', '3', 'PYP00000000', ' ', 'p:+6596737414', 'wilsonkcb8@gmail.com', '2019-03-30', '00:00:00', 'y', 'mr', 'pyp:2241766096141302', NULL, 'Koh', 'Expectant Parents Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:253153712131018', '3', 'PYP00000000', ' ', 'p:+919159924836', 'balavempu@gmail.com', '2019-03-21', '00:00:00', 'y', 'mr', 'pyp:253153712131018', NULL, 'Bala', 'School Going Kids Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:253192718793784', '3', 'PYP00000000', ' ', 'p:+6594559746', 'hyperray693@hotmail.com', '2019-03-21', '00:00:00', 'y', 'mr', 'pyp:253192718793784', NULL, 'Muhammad Zulhilmi', 'School Going Kids Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:2975361612477745', '3', 'PYP00000000', ' ', 'p:+6596996965', 'teokimyenvanessa@yahoo.com.sg', '2019-03-19', '00:00:00', 'y', 'ms', 'pyp:2975361612477745', NULL, 'Vanessa', 'General Parents', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:2982156695131570', '3', 'PYP00000000', ' ', 'p:+6596880276', 'chanelsee25@gmail.com', '2019-03-22', '00:00:00', 'y', 'mrs', 'pyp:2982156695131570', NULL, 'Chanel', 'General Parents', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:2998284086852164', '3', 'PYP00000000', ' ', 'p:+6597533232', 'lewislimguohong@yahoo.com', '2019-03-29', '00:00:00', 'y', 'mr', 'pyp:2998284086852164', NULL, 'Lewis', 'General Parents', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:3000313879982518', '3', 'PYP00000000', ' ', 'p:+6590624888', 'Trident992000@gmail.com', '2019-03-30', '00:00:00', 'y', 'mr', 'pyp:3000313879982518', NULL, 'Alvin', 'General Parents', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:3001482576532315', '3', 'PYP00000000', ' ', 'p:+6587493323', 'tanmicheal27@yahoo.com.sg', '2019-03-30', '00:00:00', 'y', 'mr', 'pyp:3001482576532315', NULL, 'Danny', 'General Parents', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:365047001006532', '3', 'PYP00000000', ' ', 'p:+6590906477', 'tunjiang.hoo@gmail.com', '2019-03-25', '00:00:00', 'y', 'mr', 'pyp:365047001006532', NULL, 'Tun Jiang', 'School Going Kids', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:406783359898757', '3', 'PYP00000000', ' ', 'p:+6594281526', 'klk1627@hotmail.com', '2019-03-28', '00:00:00', 'y', 'ms', 'pyp:406783359898757', NULL, 'Chandra', 'General Parents Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:406809359896157', '3', 'PYP00000000', ' ', 'p:+6596920669', 'feliciaw_f@yahoo.com.sg', '2019-03-29', '00:00:00', 'y', 'ms', 'pyp:406809359896157', NULL, 'Felicia', 'General Parents Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:407901266453633', '3', 'PYP00000000', ' ', 'p:+6591024107', 'keeliang290677@singnet.com.sg', '2019-03-31', '00:00:00', 'y', 'mr', 'pyp:407901266453633', NULL, 'Kee Liang', 'General Parents Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:569665483519299', '3', 'PYP00000000', ' ', 'p:+6581813350', 'sindhurk7@gmail.com', '2019-03-23', '00:00:00', 'y', 'ms', 'pyp:569665483519299', NULL, 'Sindhu', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:569686356850545', '3', 'PYP00000000', ' ', 'p:+6587497467', 'marydebbiet@yahoo.com', '2019-03-23', '00:00:00', 'y', 'mrs', 'pyp:569686356850545', NULL, 'Yram Eibbed', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:569951770157337', '3', 'PYP00000000', ' ', 'p:+6591819024', 'chen.liping84@yahoo.com', '2019-03-23', '00:00:00', 'y', 'mrs', 'pyp:569951770157337', NULL, 'Liping', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:570342463451601', '3', 'PYP00000000', ' ', 'p:+6596619486', 'reg1221@hotmail.com', '2019-03-24', '00:00:00', 'y', 'ms', 'pyp:570342463451601', NULL, 'Regina', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:570592573426590', '3', 'PYP00000000', ' ', 'p:+6597767991', 'Boonkeatloy@gmail.com', '2019-03-24', '00:00:00', 'y', 'mr', 'pyp:570592573426590', NULL, 'Simon', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:570825643403283', '3', 'PYP00000000', ' ', 'p:+6596348884', 'starmiko@hotmail.com', '2019-03-25', '00:00:00', 'y', 'mrs', 'pyp:570825643403283', NULL, 'Amy', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:570852773400570', '3', 'PYP00000000', ' ', 'p:+6584188344', 'blesilacortel@gmail.com', '2019-03-25', '00:00:00', 'y', 'ms', 'pyp:570852773400570', NULL, 'Blesila', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:571082860044228', '3', 'PYP00000000', ' ', 'p:+6587988628', 'dolphinsky90@gmail.com', '2019-03-25', '00:00:00', 'y', 'ms', 'pyp:571082860044228', NULL, 'Junie', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:571138190038695', '3', 'PYP00000000', ' ', 'p:+6596920669', 'feliciaw_f@yahoo.com.sg', '2019-03-25', '00:00:00', 'y', 'ms', 'pyp:571138190038695', NULL, 'Felicia', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:571450906674090', '3', 'PYP00000000', ' ', 'p:+6583018952', 'loque580@gmail.com', '2019-03-26', '00:00:00', 'y', 'mdm', 'pyp:571450906674090', NULL, 'Dicky', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:571506030001911', '3', 'PYP00000000', ' ', 'p:+6596314333', 'runio.acc@gmail.com', '2019-03-26', '00:00:00', 'y', 'mr', 'pyp:571506030001911', NULL, 'Khris', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:571584856660695', '3', 'PYP00000000', ' ', 'p:+6593806167', 'ola_thea0214@icloud.com', '2019-03-26', '00:00:00', 'y', 'mr', 'pyp:571584856660695', NULL, 'Thea', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:571636706655510', '3', 'PYP00000000', ' ', 'p:+6585880110', 'sgp-vsxp@hotmail.sg', '2019-03-27', '00:00:00', 'y', 'mrs', 'pyp:571636706655510', NULL, 'Vivian', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:572006043285243', '3', 'PYP00000000', ' ', 'p:+6597370249', 'chen_low_services@yahoo.com.sg', '2019-03-27', '00:00:00', 'y', 'mdm', 'pyp:572006043285243', NULL, 'Chen', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:572084033277444', '3', 'PYP00000000', ' ', 'p:+6581888178', 'satellitemoon66@gmail.com', '2019-03-27', '00:00:00', 'y', 'ms', 'pyp:572084033277444', NULL, 'Koh', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:572483489904165', '3', 'PYP00000000', ' ', 'p:+6590505645', 'thanyc@gmail.com', '2019-03-28', '00:00:00', 'y', 'ms', 'pyp:572483489904165', NULL, 'Yenching', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:573108823174965', '3', 'PYP00000000', ' ', 'p:+6592712121', 'davidchintw@gmail.com', '2019-03-30', '00:00:00', 'y', 'mr', 'pyp:573108823174965', NULL, 'David', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:574006193085228', '3', 'PYP00000000', ' ', 'p:+6584189983', 'shagedelic_83@yahoo.com', '2019-03-31', '00:00:00', 'y', 'ms', 'pyp:574006193085228', NULL, 'Amanda', 'Expectant Parents-new', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:585297588649747', '3', 'PYP00000000', ' ', 'p:94247103', 'nelsontay89@hotmail.com', '2019-03-21', '00:00:00', 'y', 'mr', 'pyp:585297588649747', NULL, 'Nelson', 'Toddlers & Newborn Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:585527525293420', '3', 'PYP00000000', ' ', 'p:+6597784166', 'gabriella_shantell@hotmail.com', '2019-03-22', '00:00:00', 'y', 'mrs', 'pyp:585527525293420', NULL, 'Gabriella', 'Toddlers & Newborn Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:585717691941070', '3', 'PYP00000000', ' ', 'p:+6581817656', 'koocindy@live.com', '2019-03-22', '00:00:00', 'y', 'ms', 'pyp:585717691941070', NULL, 'Yan Yee', 'Toddlers & Newborn Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:590122768167229', '3', 'PYP00000000', ' ', 'p:+6584987025', 'neha.harsh@yahoo.com', '2019-03-30', '00:00:00', 'y', 'ms', 'pyp:590122768167229', NULL, 'Neha', 'Toddlers & Newborn Retargeting', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:592162484528275', '3', 'PYP00000000', ' ', 'p:+6581893949', 'fionalimyin@hotmail.com', '2019-03-22', '00:00:00', 'y', 'ms', 'pyp:592162484528275', NULL, 'Fiona', 'Newborns', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:594982780912912', '3', 'PYP00000000', ' ', 'p:+6590222243', 'kevin_xiong@hotmail.com', '2019-03-28', '00:00:00', 'y', 'mr', 'pyp:594982780912912', NULL, 'Jinkai', 'Newborns', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:595843470826843', '3', 'PYP00000000', ' ', 'p:+6590505645', 'thanyc@gmail.com', '2019-03-29', '00:00:00', 'y', 'ms', 'pyp:595843470826843', NULL, 'Yen Ching', 'Newborns', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:989724651237574', '3', 'PYP00000000', ' ', 'p:+6598124642', 'boyangkong0606@gmail.com', '2019-03-21', '00:00:00', 'y', 'mr', 'pyp:989724651237574', NULL, 'Boyangkong', 'Toddlers & Newborn', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:989896091220430', '3', 'PYP00000000', ' ', 'p:+6584255569', 'adityabhanot@yahoo.com', '2019-03-21', '00:00:00', 'y', 'mr', 'pyp:989896091220430', NULL, 'Aditya', 'Toddlers & Newborn', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:990041514539221', '3', 'PYP00000000', ' ', 'p:+6596498659', 'khioshuhwen@gmail.com', '2019-03-21', '00:00:00', 'y', 'ms', 'pyp:990041514539221', NULL, 'Shuh Wen', 'Toddlers & Newborn', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:990356837841022', '3', 'PYP00000000', ' ', 'p:+6583661547', 'tanlc820@gmail.com', '2019-03-22', '00:00:00', 'y', 'ms', 'pyp:990356837841022', NULL, 'Tan', 'Toddlers & Newborn', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:990388731171166', '3', 'PYP00000000', ' ', 'p:+6596378841', 'gan.kokjin@live.com.sg', '2019-03-22', '00:00:00', 'y', 'mr', 'pyp:990388731171166', NULL, 'Eugene', 'Toddlers & Newborn', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:990953677781338', '3', 'PYP00000000', ' ', 'p:+6582334928', 'pavan.rangepalli@gmail.com', '2019-03-23', '00:00:00', 'y', 'mr', 'pyp:990953677781338', NULL, 'Pavan Kumar', 'Toddlers & Newborn', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:992706087606097', '3', 'PYP00000000', ' ', 'p:+6581880820', 'lewislimguohong@gmail.com', '2019-03-26', '00:00:00', 'y', 'mdm', 'pyp:992706087606097', NULL, 'Christine', 'Toddlers & Newborn', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO tbl_weblead_input (txt_sequence, txt_month, txt_campaign_code, txt_cust_id, txt_phone_no, txt_email, dte_sub_date, txt_sub_time, txt_is_existing, txt_salutation, txt_formid, txt_Pref_comm, txt_name, txt_product_name, txt_source, txt_processed, txt_remarks, txt_buffer_val1, txt_buffer_val2, txt_buffer_val3, txt_buffer_val4, txt_buffer_val5, txt_buffer_val6, txt_buffer_val7, txt_buffer_val8, txt_buffer_val9, txt_buffer_val10) VALUES ('pyp:992907194252653', '3', 'PYP00000000', ' ', 'p:+6591238720', 'kongaurelia.sg@gmail.com', '2019-03-26', '00:00:00', 'y', 'ms', 'pyp:992907194252653', NULL, 'Lindsey Aeryn', 'Toddlers & Newborn', 'fb', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

